### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by Suvi-dha** [ysbecca/py-wsi#1]
Hi, I am installing py-wsi using pip, but I am encountering following error 
``(tensorflow) C:\>pip install py-wsi
Collecting py-wsi
  Using cached https://files.pythonhosted.org/packages/15/d2/70508f9fd4aa01e21c89f421f4c5d3a5f533af0eed6ea6bffae92c4a9678/py_wsi-0.21.tar.gz
Collecting shapely (from py-wsi)
  Using cached https://files.pythonhosted.org/packages/7d/3c/0f09841db07aabf9cc387662be646f181d07ed196e6f60ce8be5f4a8f0bd/Shapely-1.6.4.post1.tar.gz
    **Complete output from command python setup.py egg_info:**
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\IIIT\AppData\Local\Temp\pip-build-wxoplbyb\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\IIIT\AppData\Local\Temp\pip-build-wxoplbyb\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Users\IIIT\Anaconda3\envs\tensorflow\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    **OSError: [WinError 126] The specified module could not be found**

    ----------------------------------------
**Command "python setup.py egg_info" failed with error code 1 in C:\Users\IIIT\AppData\Local\Temp\pip-build-wxoplbyb\shapely\`** 

I have all the dependencies already satisfied.

**Comment by ysbecca** [comment]
Hi, if you try installing shapely by itself, do you get any errors?

`pip install shapely`

Also, for your awareness, I am soon releasing an updated version of py-wsi which will manage memory better when sampling patches.

**Comment by Suvi-dha** [comment]
No, I am still encountering the same errors 

> (base) C:\>pip install shapely
Collecting shapely
  Using cached https://files.pythonhosted.org/packages/7d/3c/0f09841db07aabf9cc387662be646f181d07ed196e6f60ce8be5f4a8f0bd/Shapely-1.6.4.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\IIIT\AppData\Local\Temp\pip-install-6l2cz6je\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\IIIT\AppData\Local\Temp\pip-install-6l2cz6je\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "c:\users\iiit\anaconda3\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\IIIT\AppData\Local\Temp\pip-install-6l2cz6je\shapely\

**Comment by ysbecca** [comment]
Great. Do watch out for the update coming out in the next week, I will be changing the way py-wsi samples data to allow for larger datasets (and more accurately pre-computed memory requirements).

**Comment by Suvi-dha** [comment]
Cool. I will be looking out for the updates. Also, I am trying to convert my annotation files into coco style annotation format. I am also trying to break annotation files which correspond to the relative patch in the original image. 
If you could add these functionalities in your update. That would help people who want to try such datasets on vast range of algorithms.
