### ISSUE TITLE
MapFullError

### ISSUE THREAD

**Issue by harishprabhala** [ysbecca/py-wsi#13]
Hi,

When I increase the patch size to 128, I get this error

MapFullError: mdb_put: MDB_MAP_FULL: Environment mapsize limit reached

<img width="1680" alt="screen shot 2018-11-02 at 2 53 05 pm" src="https://user-images.githubusercontent.com/26444096/47906370-17847580-deaf-11e8-99b8-5f6e4e2d5707.png">

**Comment by ysbecca** [comment]
Hi, I think it's possible that it's due to your Jupyter notebook memory limitation. Could you try running it in a Python script outside of a notebook and see if the error still occurs?
