### ISSUE TITLE
Unable to change the storage type to disk 

### ISSUE THREAD

**Issue by Mounika2405** [ysbecca/py-wsi#14]
Hi,
 I'm unable to change the storage type to disk.
![image](https://user-images.githubusercontent.com/33863436/49007814-66fa5080-f192-11e8-8f3e-47a0375807cf.png)

 The init signature doesn't show storage_type parameter
![image](https://user-images.githubusercontent.com/33863436/49008007-d5d7a980-f192-11e8-8af1-03e018c93010.png)

Please help me in getting access to this storage_type.

Thanks.

**Comment by ysbecca** [comment]
Hi @Mounika2405, looks like you need to update your version of py_wsi! If you previously forked py-wsi, make sure you pull the most recent version. Older versions did not support disk or HDF5.

**Comment by Mounika2405** [comment]
It worked 👍 Thank you so much :)
