### ISSUE TITLE
Issue regarding pocessing of .scn( Leica) Images

### ISSUE THREAD

**Issue by hitesha14** [ysbecca/py-wsi#15]
###  Issues with .scn WSI for Image patch generation using the xml.
I would like to know if .scn image which is also a Whole Slide Image can be processed by py_wsi apart from the .svs images. Since .scn images can also be viewed and annotated using Aperio Imagescope. 
I would be extremely grateful to know if this functionality already exists in py_wsi or it could be added as a feature for processing the pathological Whole Slide Images?
My research work is on this domain and it would be really helpful if you could integrate such capabilities incase it doesn't exist already. I am actually unable to proceed with my research work due to this issue.

Awaiting your reply and thoughts about it. Please do let me know. @ysbecca

**Comment by ysbecca** [comment]
Hello @hitesha14, py_wsi does not support .scn images, and I have no immediate plans to include it. I would suggest:

1. Fork py_wsi and add the integration yourself. I've had a quick look at OpenSlide Python, and it should be very simple, as OpenSlide *does* read .scn images! Just look for where I look for .svs images, and replace that with .scn.
2. Can you convert .scn to .svs? The annotations are still in the same format so only the images are different. I say "only," but depending on how many images you have this could be a hassle.

If you can do (1) I would strongly recommend it.

**Comment by hitesha14** [comment]
I have done with the help of the method 1 as suggested by you. I am able to process the images
