### ISSUE TITLE
error installation on ubuntu

### ISSUE THREAD

**Issue by waferson** [ysbecca/py-wsi#19]
please help me, I had it:

`effer@jeffer-sky:~/Descargas$ pip install py_wsi
Collecting py_wsi
  Using cached https://files.pythonhosted.org/packages/32/f4/a4f692b8d7791df38874e678e28c60783284ca4a5fe4f083214f45e4ede2/py_wsi-1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Sc0b5n/py-wsi/setup.py", line 12, in <module>
        with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Sc0b5n/py-wsi/`

**Comment by ysbecca** [comment]
Hmm, what version of Python do you have? Also, I would strongly suggest NOT using pip to install py_wsi, as I have not updated that version. I recommend forking the Git repo and downloading the source code and using that version directly instead.
