### ISSUE TITLE
storage_type

### ISSUE THREAD

**Issue by anfegon** [ysbecca/py-wsi#20]
Hi Rebecca,

I have problems when I use the storage_type option but if I don't write storage_type='lmdb' or storage_type='disk' py_wsi.Turtle works perfectly. I would like to saves patches as PNG files, so I would very grateful to know what can be the problem. This is the error I get:

turtle = py_wsi.Turtle(file_dir, db_location, db_name, xml_dir=xml_dir, storage_type='lmdb')

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-85-80da53bf2ab2> in <module>

----> 1 turtle = py_wsi.Turtle(file_dir, db_location, db_name, xml_dir=xml_dir, storage_type='lmdb')

TypeError: __init__() got an unexpected keyword argument 'storage_type'

**Comment by ysbecca** [comment]
Apologies for the delayed response, somehow I missed this! You need to update the version of py-wsi so that it recognises the `storage_type` parameter. Re-pull from the master branch. :)
