### ISSUE TITLE
Error when creating patches from full resolution image

### ISSUE THREAD

**Issue by khuhu** [ysbecca/py-wsi#21]
Hi,

I'm trying to use py-wsi to write patches to my disk following your jupyter notebook example. My image (40x) has 18 levels, however when I try to use the line of code for the 18th level, I get an error that says the requested level does not exist. I wondering if there is some type of indexing difference? Below is the code I ran: 

level=18
patch_size=32
overlap=0
turtle.sample_and_store_patches(patch_size, level ,overlap, limit_bounds=True)
TCGA-LL-A7T0-01Z-00-DX1.B03BBA63-ACF4-4BCA-9F2B-F631F0C6A25C.svs [py-wsi error]: requested level does not exist. Number of slide levels: 18
[py-wsi error]: no patches sampled from  TCGA-LL-A7T0-01Z-00-DX1.B03BBA63-ACF4-4BCA-9F2B-F631F0C6A25C.svs . Continuing.

The svs file can be found from the genomic data commons if you wanted to recreate the error. Let me know if you have a fix.

Thanks,
Kevin

**Comment by ysbecca** [comment]
Hi Kevin, my apologies for the delayed response! I believe the error is correct, and it's due to the indexing as you suspected. There are 18 levels, and indexed from 0 - 17. I should make the error message more descriptive... if you try level 17 you should find that it's alright. Let me know.

**Comment by NyiNyiNaing86** [comment]
Hi, madam
I am trying to use py_wsi,
I copy from Example usage of py-wsi.
I got following error:
TypeError                                 Traceback (most recent call last)
<ipython-input-13-0fba6c173440> in <module>()
      1 #Create a new py-wsi manager object for our collection of svs images. It's called a turtle. We will use the storage option LMDB
      2 #(which is also set by default, for backwards compatibility.)
----> 3 turtle = py_wsi.Turtle(file_dir, db_location, db_name, xml_dir=xml_dir, label_map=label_map, storage_type='lmdb')

TypeError: __init__() got an unexpected keyword argument 'storage_type'

please how can I fix that problem, madam
Thank you

**Comment by ysbecca** [comment]
Hello. You need to download the most recent version of py_wsi, by cloning or forking the github repository, **not** installing using pip.
