### ISSUE TITLE
Calculating the number of patches.

### ISSUE THREAD

**Issue by Hyungsik-Jung** [ysbecca/py-wsi#22]
Hello, @ysbecca . First of all, thanks for your great works. 
I have a question regard to calculating the number of total patches.
For understanding, I pasted my results as below.

======================================================
Total WSI images:    1
File names:          ['01_01_0088.svs']
Setting patch size 256 and tile size 256
Level count:         17
Level tiles:         ((1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (1, 1), (2, 2), (4, 3), (7, 6), (14, 11), (27, 22), (53, 43), (105, 86), (210, 172))
Level dimensions:    ((1, 1), (2, 2), (4, 3), (7, 6), (14, 11), (27, 22), (53, 43), (105, 86), (210, 172), (420, 344), (840, 687), (1680, 1374), (3360, 2747), (6720, 5493), (13440, 10986), (26879, 21971), (53757, 43941))
Patch size: 256
01_01_0088.svs 
============ Patches Dataset Stats ===========
Total patches sampled:                     130
Patches saved to:                          /data/JHS/paip_2019/Phase1/py_wsi/0088/
Patches saved with prefix:                 patch_db

Time usage: 0:00:15

I set the level as 12. As I understand, 'Total patches sampled' should be 42(=7*6), because the dimension of 12th level tiles is [7 by 6]. However, the number of total patches is 130. 
I want to know the exact process to calculate the number of patches.

Thank you.

**Comment by ysbecca** [comment]
Hi @Hyungsik-Jung, someone else just raised a similar question, I will think of a way to make this more clear for users in the future, or change the API. There are 12 levels, but actually they are zero-indexed (level 0 to 11). So you actually want to set the level to 11. With level = 12, you are sampling from level with dimensions  (14, 11), resulting in at most 14*11 = 154 tiles (remember that there is thresholding applied to avoid sampling from blank slide).

**Comment by Hyungsik-Jung** [comment]
Thanks for your quick answer. 
But I still didn't get how '**thresholding**' works. Can you explain more about this issue?
Furthermore, is there any method to restore original image from the set of patches?
I really appreciate you for sharing amazing works.

Thank you

**Comment by ysbecca** [comment]
I just checked the code... actually, the thresholding in py-wsi is the limit_bounds flag in the OpenSlide. I find it very conservative (really only avoids sampling the patches which have absolutely nothing in them). You can read about it [here in the API](https://openslide.org/api/python/).

My next update to py-wsi will use Otsu masks to sample from tissue only, which is currently the most commonly used thresholding approach.

Py-wsi does not automatically restore images... although that's an idea for future updates -- I will definitely consider making a function which takes predictions and generates a heat map prediction image which could be overlaid (and probably downsampled). In principle, you have what you need to reconstruct already -- each tile coordinates are stored in the DB, and you know the tile grid dimensions.
