### ISSUE TITLE
Issue with reading patch_meta_db

### ISSUE THREAD

**Issue by sheikmohdimran** [ysbecca/py-wsi#26]
Hi,

your code `store.py` has 
`def read_lmdb(location, name):`
`        ''' Read-only allows for multiple consecutive reads. '''`
`        return lmdb.open(name, readonly=True)`

Which prevents from opening the lmdb. To make this work I have changed this to 

`def read_lmdb(location, name):`
`        ''' Read-only allows for multiple consecutive reads. '''`
`        return lmdb.open(location+'/'+name, readonly=True)`

Is this expected or am I doing something wrong.

**Comment by ysbecca** [comment]
This looks like an error. Thanks for catching and letting me know! I've updated the code and pushed to master. I don't add the "/" because in other places I assume the location should specify a folder, ending in a slash.

`return lmdb.open(location + name, readonly=True)`
