### ISSUE TITLE
py_wsi could not import in python 3.7

### ISSUE THREAD

**Issue by WaqasHU** [ysbecca/py-wsi#30]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-1943d99729e9> in <module>
----> 1 import py_wsi

ModuleNotFoundError: No module named 'py_wsi'
i dont know why py_wsi cannot be imported in latest version...even i tried to switch kernel to python 3.6.1 but failed

**Comment by ysbecca** [comment]
I missed this, so extremely late, but in case this helps people in the future: **pip** does not store the latest version of py_wsi. If you clone the repository you will have the latest version.

**Comment by WaqasHU** [comment]
Can you give me some time on TeamViewer...when you get free anytime

**Comment by ysbecca** [comment]
Hi @WaqasHU, sorry, I don't provide this kind of support. Am happy to receive emails with specific questions if you can write them out.

**Comment by WaqasHU** [comment]
Thanks...i will email you detail information of problem what i am facing
since 8 months...i have tried very much but failed to get labeled patches
from slide...even i get patches but not labeled...
