### ISSUE TITLE
Redundant writing to HDF5 and LMDB files. 

### ISSUE THREAD

**Issue by mmikailov** [ysbecca/py-wsi#33]
Hi Rebecca,

I am looking at the master branch of your code, py-wsi.

In file patch_reader.py lines ##156-162 are within the while-loop which starts at line #125:

        # Write to HDF5 files all in one go.
        if storage_option == 'hdf5':
            save_to_hdf5(db_location, patches, coords, file_name[:-4], labels)

        # Need to save tile dimensions if LMDB for retrieving patches by key.
        if storage_option == 'lmdb':
            save_meta_in_lmdb(meta_env, file_name[:-4], [x_tiles, y_tiles])

Which leads to redundant writing to HDF5 and LMDB files. 

Is this done deliberately?

**Comment by ysbecca** [comment]
Thanks for catching this. I have corrected.
