### ISSUE TITLE
error while sampling and storing patches 

### ISSUE THREAD

**Issue by shivampuri20** [ysbecca/py-wsi#34]
~\Desktop\py-wsi-master\py_wsi\store.py in new_lmdb(location, name, map_size_bytes)
     58 
     59 def new_lmdb(location, name, map_size_bytes):
---> 60     return lmdb.open(location + name, map_size=map_size_bytes)
     61 
     62 def print_lmdb_keys(env):

Error: /Users/shiva/Project1/py_wsi/patch_db_meta: The requested operation cannot be performed on a file with a user-mapped section open.

So this error occured while sampling and storing patches .
please look at it

**Comment by ysbecca** [comment]
This error messages indicates the lmdb was not closed properly. Apologies for such a late response. You will need to either close the database file and then re-run, or delete the file and then re-create it.
