### ISSUE TITLE
Working with TIFF files

### ISSUE THREAD

**Issue by dannellyz** [ysbecca/py-wsi#35]
Is there a way to add functionality for other files types beyond SVI? I am working with TIFF files and see that I can change file type in one of the modules, but curious about other functionality. I am not very experienced with WSI so I am not sure if this is a big ask. Thanks!

`def __get_files_from_dir(self, file_dir, file_type='.svs'):`

**Comment by ysbecca** [comment]
Py-wsi uses the Python binding of the OpenSlide C package (https://openslide.org/), so any file format that OpenSlide supports could be supported by py-wsi. TIF files are supported by OpenSlide. It might require some tweaks to make it work out of the box though as py-wsi was built with .svs in mind.... I welcome you to fork the repository and play around with it.
