### ISSUE TITLE
highest level

### ISSUE THREAD

**Issue by gnusnomis** [ysbecca/py-wsi#38]
Hi Rebecca, thanks for the amazing code I've been using it for cytopathology slides to extract images for CNN, and it's almost perfect for liquid based cytology samples. I have a question, the highest level for most of the slides is 17. Except for on an odd occasion, the highest level is 18. Is there a way to to set the level to the highest level automatically ? I run a batch (about 10 files) of .svs files at a time, and this would be very helpful. Thanks so much in advance! 
Simon

**Comment by ysbecca** [comment]
Responded to in comment chain on my blog post: https://ysbecca.github.io/programming/2018/05/22/py-wsi.html
