### ISSUE TITLE
how to merge tiles back to whole slide image (usage_issue)

### ISSUE THREAD

**Issue by talkhanz** [ysbecca/py-wsi#41]
Dear @ysbecca I am looking to extract tiles from a .svs file, perform segmentation on the tile and then stitch all the tiles back so they reappear as the whole slide image in the correct order. Is it possible to do that with py_wsi? I am asking since I could not locate code for stitching/merging the code in the repo.

**Comment by ysbecca** [comment]
Hi @talkhanz, unfortunately py_wsi doesn't do re-stitching. py_wsi does store the row, col coordinates of the sampled tiles which will be used for the re-stitching.
