### ISSUE TITLE
svs doubt

### ISSUE THREAD

**Issue by KARTHI2710** [ysbecca/py-wsi#47]
It is possible to create multiple png file to svs file and add some meta data to it. meta data like patientname,age,like that

**Comment by ysbecca** [comment]
Apologies for the delayed response, I'm no longer regularly maintaining this codebase. To reply - if I understand your question, you can't add meta data to the png file, unless you save it in the filename. I strongly recommend saving meta data in a separate database or separate files, and linking to the png files.
