### ISSUE TITLE
Return of retrieve_tile_dimensions

### ISSUE THREAD

**Issue by g8a9** [ysbecca/py-wsi#6]
Hi,

I don't know if it was intentional or not, but retrieve_tile_dimensions can return two or three parameters:
```python
...
if not self.__check_file_found(file_name):
	return (0, 0)
...
```
making impossibile to unpack them (and generating a ValueError) in code such:
```python
level_count, level_tiles, level_dims = turtle.retrieve_tile_dimensions('A01.svs', patch_size=128)
print("Level count:         " + str(level_count))
print("Level tiles:         " + str(level_tiles))
print("Level dimensions:    " + str(level_dims))
```
Maybe, in that specific case, the function could Raise a custom message RuntimeError if the file is not found.

**Comment by ysbecca** [comment]
Thanks, good point. I have just pushed an update. It now returns reasonable values for a file not found: `level_count = 0, level_tiles = [], level_dims = []`

**Comment by g8a9** [comment]
Good! Closing.
