### ISSUE TITLE
Minor issue with tab indentation

### ISSUE THREAD

**Issue by mingrui** [ysbecca/py-wsi#9]
Hi!
Thanks for this project, I find it very useful.

Just a minor issue with tab indentation in the python files, I think it's not too late to convert all indentation from tabs to spaces, as per PEP-0008 https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces

**Comment by ysbecca** [comment]
Ah. Very good point, thanks for pointing it out. I hope this isn't keeping you from using the project for now... I can't promise when I'll get around to this - earliest may be when I push the HDF5 functionality, which may be in mid-November.

**Comment by ysbecca** [comment]
Alternately, you are welcome to convert and submit a pull request which I'll gladly accept. :)

**Comment by mingrui** [comment]
Just submitted a pull request : )

**Comment by ysbecca** [comment]
Excellent, thanks so much! Feel free to add additional functionality in the future which you think would be useful and I'll happily review.
